
INSERT INTO config_param_system VALUES (1, 'arc_searchnodes', '0.5', 'float', 'edit', NULL, NULL, NULL, 'Arc searchnodes buffer:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_param_system VALUES (2, 'arc_searchnodes_control', 'true', 'boolean', 'edit', NULL, NULL, NULL, 'Arc searchnodes control:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_param_system VALUES (3, 'samenode_init_end_control', 'false', 'boolean', 'edit', NULL, NULL, NULL, 'Arc same node init end control:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_param_system VALUES (5, 'state_topocontrol', 'true', 'boolean', 'edit', NULL, NULL, NULL, 'State topocontrol:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_param_system VALUES (4, 'edit_topocontrol_dsbl_error', 'true', 'boolean', 'edit', NULL, NULL, NULL, 'Topocontrol error:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_param_system VALUES (6, 'node_search_streetaxis', '5', 'numeric', 'edit', NULL, NULL, NULL, 'Node search streetaxis:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO config_param_system VALUES (7, 'light_separate_distance', '0.7', 'numeric', 'edit', NULL, NULL, NULL, 'Light separate distance:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);



INSERT INTO man_addfields_cat_datatype VALUES ('integer', NULL);
INSERT INTO man_addfields_cat_datatype VALUES ('text', NULL);
INSERT INTO man_addfields_cat_datatype VALUES ('date', NULL);
INSERT INTO man_addfields_cat_datatype VALUES ('boolean', NULL);
INSERT INTO man_addfields_cat_datatype VALUES ('numeric', NULL);


INSERT INTO sys_typevalue (id, typevalue, idval, descript) VALUES (1, 'feature_type', 'ARC', NULL);
INSERT INTO sys_typevalue (id, typevalue, idval, descript) VALUES (2, 'feature_type', 'NODE', NULL);
INSERT INTO sys_typevalue (id, typevalue, idval, descript) VALUES (3, 'system_id', 'PANELBOARD', NULL);
INSERT INTO sys_typevalue (id, typevalue, idval, descript) VALUES (4, 'system_id', 'REGISTER', NULL);
INSERT INTO sys_typevalue (id, typevalue, idval, descript) VALUES (5, 'system_id', 'LAMPPOST', NULL);
INSERT INTO sys_typevalue (id, typevalue, idval, descript) VALUES (6, 'system_id', 'LIGHTPOINT', NULL);
INSERT INTO sys_typevalue (id, typevalue, idval, descript) VALUES (7, 'system_id', 'LINE', NULL);


INSERT INTO audit_cat_param_user VALUES ('state_topocontrol', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO audit_cat_param_user VALUES ('node_search_streetaxis', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO audit_cat_param_user VALUES ('samenode_init_end_control', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO audit_cat_param_user VALUES ('light_separate_distance', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO audit_cat_param_user VALUES ('edit_topocontrol_dsbl_error', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO audit_cat_param_user VALUES ('arc_searchnodes_control', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO audit_cat_param_user VALUES ('arc_searchnodes', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO audit_cat_table VALUES ('om_visit_typevalue', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('version', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_value_criticity', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_state_arc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_state_node', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_ui_node', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_ui_arc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_state_element', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_ui_element', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_ui_document', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_ext_streetaxis', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_ext_address', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_ui_element_x_node', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_ui_element_x_arc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_ui_doc_x_node', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_ui_doc_x_arc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('v_ui_doc_x_visit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('config_param_system', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_parameter', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit', NULL, NULL, 'role_om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_cat', NULL, NULL, 'role_om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_x_arc', NULL, NULL, 'role_om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_x_node', NULL, NULL, 'role_om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('selector_date', NULL, NULL, 'role_basic', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('selector_state', NULL, NULL, 'role_basic', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('ve_arc', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('ve_arc_linia', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('ve_dma', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('ve_element', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('ve_node', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('ve_node_arqueta', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('ve_node_columna', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('ve_node_punto_luz', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('ve_node_quadre', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('value_state_type', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('value_state', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('sys_typevalue', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_event', NULL, NULL, 'role_om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_event_photo', NULL, NULL, 'role_om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_file', NULL, NULL, 'role_om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_lot', NULL, NULL, 'role_om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_lot_x_arc', NULL, NULL, 'role_om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_lot_x_node', NULL, NULL, 'role_om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_filetype_x_extension', NULL, NULL, 'role_om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_class_x_parameter', NULL, NULL, 'role_om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_class', NULL, NULL, 'role_om', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_parameter_x_parameter', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_parameter_form_type', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_parameter_cat_action', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_parameter_index', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('om_visit_parameter_type', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('man_addfields_parameter', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('man_addfields_value', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('man_addfields_cat_datatype', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('ext_address', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('ext_type_street', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('ext_streetaxis', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('ext_municipality', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('exploitation_x_user', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('exploitation', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('element', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('element_x_node', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('element_x_arc', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('element_type', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('doc_x_visit', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('doc_x_node', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('doc_x_arc', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('doc_type', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('doc', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('dma', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('config_param_user', NULL, NULL, 'role_basic', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('cat_work', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('cat_user', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('cat_soil', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('cat_owner', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('cat_node', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('cat_mat_node', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('cat_mat_element', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('cat_mat_arc', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('cat_feature', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('cat_builder', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('cat_element', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('cat_arc', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('cat_addfields_typevalue', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('audit_cat_error', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('audit_cat_table', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('audit_cat_param_user', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('audit_cat_function', NULL, NULL, 'role_admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('audit_log_data', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('arc', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);
INSERT INTO audit_cat_table VALUES ('node', NULL, NULL, 'role_edit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);